var dataSet=[
    {
        "id": "b1",
        "name": "Bagel and cream cheese",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/uvVi",
        "price": "15.50",
        "category": "breakfast",
    },
    {
        "id": "b2",
        "name": "Breakfast sandwich",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/SvY6",
        "price": "18.85",
        "category": "breakfast",
    },
    {
        "id": "b3",
        "name": "Baked chiken",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/bIJG",
        "price": "13.45",
        "category": "breakfast",
    },
    {
        "id": "b4",
        "name": "Egg Benedict",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/I4uG",
        "price": "11.26",
        "category": "breakfast",
    },
    {
        "id": "b5",
        "name": "Toast Croissant Fried egg",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/X5_C",
        "price": "20.12",
        "category": "breakfast"
    },
    {
        "id": "b6",
        "name": "Fried Egg Toast Brunch Full",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/frKh",
        "price": "30.25",
        "category": "breakfast",
    },
    {
        "id": "l1",
        "name": "Healthy Meal Plan",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/mSFE",
        "price": "41.50",
        "category": "lunch",
    },
    {
        "id": "l2",
        "name": "Fried Chicken Bento",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/fH5E",
        "price": "45.26",
        "category": "lunch",
    },
    {
        "id": "l3",
        "name": "Tarragon-Rubbed-Salmon",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/bXag",
        "price": "50",
        "category": "lunch",
    },
    {
        "id": "l4",
        "name": "Beef Steak",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/KXPW",
        "price": "48",
        "category": "lunch",
    },
    {
        "id": "l5",
        "name": "Honey-Soy-Glazed Salmon with Peppers",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/XJCE",
        "price": "56.45",
        "category": "lunch",
    },
    {
        "id": "l6",
        "name": "Indian Lunch",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/8h23",
        "price": "41.80",
        "category": "lunch",
    },
    {
        "id": "d1",
        "name": "Salmon with grapefruit and Lentil Salad",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/g9FW",
        "price": "35",
        "category": "dinner",
    },
    {
        "id": "d2",
        "name": "Lemony Salmon Piccata",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/Qx9c",
        "price": "38",
        "category": "dinner",
    },
    {
        "id": "d3",
        "name": "Pork Tenderloin With Quinoa Pilaf",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/k3Qa",
        "price": "40.50",
        "category": "dinner",
    },
    {
        "id": "d4",
        "name": "French fries with cheese",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/BVpt",
        "price": "45.50",
        "category": "dinner",
    },
    {
        "id": "d5",
        "name": "Garlic Butter Baked Salmon",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/AW8p",
        "price": "32.50",
        "category": "dinner",
    },
    {
        "id": "d6",
        "name": "Baked Chicken",
        "details": "Foods You Need To Eat Before You Die",
        "image":"https://gdurl.com/o9zL",
        "price": "41.50",
        "category": "dinner",
    },
    
];
export default dataSet;


