var dataSet=[
    {
        "id": "b1",
        "name": "Bagel and cream cheese",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Breakfast/breakfast1.png",
        "price": "15.50",
        "category": "breakfast",
    },
    {
        "id": "b2",
        "name": "Breakfast sandwich",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Breakfast/breakfast2.png",
        "price": "18.85",
        "category": "breakfast",
    },
    {
        "id": "b3",
        "name": "Baked chiken",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Breakfast/breakfast3.png",
        "price": "13.45",
        "category": "breakfast",
    },
    {
        "id": "b4",
        "name": "Egg Benedict",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Breakfast/breakfast4.png",
        "price": "11.26",
        "category": "breakfast",
    },
    {
        "id": "b5",
        "name": "Toast Croissant Fried egg",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Breakfast/breakfast5.png",
        "price": "20.12",
        "category": "breakfast"
    },
    {
        "id": "b6",
        "name": "Fried Egg Toast Brunch Full",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Breakfast/breakfast6.png",
        "price": "30.25",
        "category": "breakfast",
    },
    {
        "id": "l1",
        "name": "Healthy Meal Plan",
        "details": "Foods You Need To Eat Before You Die",
        "image":"lunch1.png",
        "price": "41.50",
        "category": "lunch",
    },
    {
        "id": "l2",
        "name": "Fried Chicken Bento",
        "details": "Foods You Need To Eat Before You Die",
        "image":"lunch2.png",
        "price": "45.26",
        "category": "lunch",
    },
    {
        "id": "l3",
        "name": "Tarragon-Rubbed-Salmon",
        "details": "Foods You Need To Eat Before You Die",
        "image":"lunch3.png",
        "price": "50",
        "category": "lunch",
    },
    {
        "id": "l4",
        "name": "Beef Steak",
        "details": "Foods You Need To Eat Before You Die",
        "image":"lunch4.png",
        "price": "48",
        "category": "lunch",
    },
    {
        "id": "l5",
        "name": "Honey-Soy-Glazed Salmon with Peppers",
        "details": "Foods You Need To Eat Before You Die",
        "image":"lunch5.png",
        "price": "56.45",
        "category": "lunch",
    },
    {
        "id": "l6",
        "name": "Indian Lunch",
        "details": "Foods You Need To Eat Before You Die",
        "image":"lunch6.png",
        "price": "41.80",
        "category": "lunch",
    },
    {
        "id": "d1",
        "name": "Salmon with grapefruit and Lentil Salad",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Dinner/dinner1.png",
        "price": "35",
        "category": "dinner",
    },
    {
        "id": "d2",
        "name": "Lemony Salmon Piccata",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Dinner/dinner2.png",
        "price": "38",
        "category": "dinner",
    },
    {
        "id": "d3",
        "name": "Pork Tenderloin With Quinoa Pilaf",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Dinner/dinner3.png",
        "price": "40.50",
        "category": "dinner",
    },
    {
        "id": "d4",
        "name": "French fries with cheese",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Dinner/dinner4.png",
        "price": "45.50",
        "category": "dinner",
    },
    {
        "id": "d5",
        "name": "Garlic Butter Baked Salmon",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Dinner/dinner5.png",
        "price": "32.50",
        "category": "dinner",
    },
    {
        "id": "d6",
        "name": "Baked Chicken",
        "details": "Foods You Need To Eat Before You Die",
        "image":"Dinner/dinner6.png",
        "price": "41.50",
        "category": "dinner",
    },
    
];
export default dataSet;


